use crate::{RunReport, Severity};
use anyhow::Result;
use std::{fs, path::Path};

pub fn write_report(report: &RunReport, out: &Path) -> Result<()> {
    fs::create_dir_all(out)?;
    fs::write(out.join("report.json"), serde_json::to_vec_pretty(report)?)?;
    fs::write(out.join("index.html"), render(report))?;
    Ok(())
}

pub fn render(report: &RunReport) -> String {
    let status = if report.passed { "PASS" } else { "CHECK" };
    let status_class = if report.passed { "pass" } else { "fail" };
    let mut runs = String::new();
    for run in &report.runs {
        let mut rows = String::new();
        for step in &run.steps {
            let severity = step
                .findings
                .iter()
                .map(|f| &f.severity)
                .max_by_key(|s| match s {
                    Severity::Pass => 0,
                    Severity::Warning => 1,
                    Severity::Failure => 2,
                })
                .unwrap_or(&Severity::Pass);
            let (word, class) = match severity {
                Severity::Pass => ("Pass", "pass"),
                Severity::Warning => ("Review", "warn"),
                Severity::Failure => ("Blocked", "fail"),
            };
            let findings = step
                .findings
                .iter()
                .map(|f| {
                    format!(
                        "<li><span>{}</span> {}</li>",
                        finding_label(&f.kind),
                        esc(&f.message)
                    )
                })
                .collect::<String>();
            rows.push_str(&format!(r#"<article class="step {class}"><header><span class="number">{}</span><div><h3>{} · <kbd>{}</kbd></h3><p>{}</p></div><strong>{word}</strong></header><dl><div><dt>Focus</dt><dd><code>{}</code></dd></div><div><dt>Name</dt><dd>{}</dd></div><div><dt>Box</dt><dd>{:.0}×{:.0} at {:.0},{:.0}</dd></div><div><dt>Scroll path</dt><dd>{}</dd></div></dl><ul>{findings}</ul></article>"#,
                step.number, esc(&step.element), esc(&step.key), esc(&step.selector), esc(&step.selector),
                if step.accessible_name.is_empty() { "—".into() } else { esc(&step.accessible_name) }, step.rect.width, step.rect.height, step.rect.x, step.rect.y,
                if step.scrollable { "available" } else { "not needed / unavailable" }
            ));
        }
        runs.push_str(&format!(r#"<section class="run" aria-labelledby="zoom-{z}"><div class="run-title"><div><p class="eyebrow">Replay evidence</p><h2 id="zoom-{z}">{z}% zoom</h2></div><p><strong>{f}</strong> failures · <strong>{w}</strong> warnings<br><span>{vp}</span></p></div><figure><img src="{shot}" alt="Final browser viewport after replaying the workflow at {z}% zoom" width="1280" height="900"><figcaption>Final focused state · screenshot kept in this report folder</figcaption></figure><div class="steps">{rows}</div></section>"#,
            z=run.zoom, f=run.failures, w=run.warnings, vp=esc(&run.viewport_css), shot=esc(&run.screenshot)));
    }
    format!(
        r##"<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{name} · Zoom Workflow Check report</title><style>{CSS}</style></head><body><a class="skip" href="#report">Skip to report</a><header class="mast"><div class="brand">Z/WC · field sheet</div><div class="stamp {status_class}">{status}</div></header><main id="report"><section class="summary"><p class="eyebrow">Keyboard workflow · local evidence</p><h1>{name}</h1><p class="url">{url}</p><div class="totals"><span><strong>{failures}</strong> failures</span><span><strong>{warnings}</strong> warnings</span><span><strong>{count}</strong> zoom runs</span></div><p class="disclaimer">{disclaimer}</p></section><div class="runs">{runs}</div></main><footer><p>Generated by Zoom Workflow Check {version} · {date}</p><p>Nothing in this report was uploaded.</p></footer></body></html>"##,
        name = esc(&report.workflow),
        url = esc(&report.url),
        failures = report.failures,
        warnings = report.warnings,
        count = report.runs.len(),
        disclaimer = esc(&report.disclaimer),
        version = esc(&report.tool_version),
        date = esc(&report.generated_at)
    )
}

fn finding_label(kind: &crate::FindingKind) -> &'static str {
    match kind {
        crate::FindingKind::FocusOrder => "Order",
        crate::FindingKind::FocusName => "Name",
        crate::FindingKind::FocusVisible => "Indicator",
        crate::FindingKind::ViewportClipping => "Viewport",
        crate::FindingKind::AncestorClipping => "Clipping",
        crate::FindingKind::Obscured => "Obscured",
        crate::FindingKind::Runtime => "Runtime",
    }
}

fn esc(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

const CSS: &str = r#"
:root{color-scheme:light;--paper:#f3ebd8;--sheet:#fff9ec;--ink:#18221d;--muted:#5c625a;--blue:#095d9a;--orange:#d94b21;--leaf:#266444;--bruise:#812d42;--yellow:#f2c94c;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--ink);background:var(--paper)}*{box-sizing:border-box}body{margin:0;background-color:var(--paper);background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32'%3E%3Ccircle cx='4' cy='6' r='.7' fill='%2318221d' fill-opacity='.1'/%3E%3C/svg%3E");font-size:16px;line-height:1.5}.skip{position:absolute;left:8px;top:-80px;background:var(--ink);color:#fff;padding:12px;z-index:10}.skip:focus{top:8px}.mast,main,footer{width:min(1160px,calc(100% - 32px));margin:auto}.mast{display:flex;justify-content:space-between;align-items:center;padding:24px 0;border-bottom:3px solid var(--ink);text-transform:uppercase;font-weight:800}.stamp{border:3px solid;padding:8px 12px;transform:rotate(-2deg)}.stamp.pass{color:var(--leaf)}.stamp.fail{color:var(--bruise)}.summary{padding:64px 0 48px;max-width:880px}.eyebrow{text-transform:uppercase;letter-spacing:.13em;font-size:.78rem;font-weight:800;color:var(--blue)}h1,h2,h3,p{margin-top:0}h1{font-family:"Arial Black","Arial Narrow",sans-serif;text-transform:uppercase;font-size:clamp(2.7rem,8vw,5.5rem);line-height:.9;letter-spacing:-.05em;margin-bottom:24px}h2{font:900 2rem/1 "Arial Black","Arial Narrow",sans-serif;text-transform:uppercase}.url{overflow-wrap:anywhere;color:var(--muted)}.totals{display:flex;flex-wrap:wrap;gap:8px;margin:24px 0}.totals span{border:2px solid;padding:10px 14px;background:var(--sheet)}.disclaimer{max-width:68ch;border-left:8px solid var(--orange);padding-left:16px}.runs{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;align-items:start}.run{background:var(--sheet);border:3px solid var(--ink);box-shadow:7px 7px 0 var(--blue);padding:20px}.run-title{display:flex;justify-content:space-between;gap:16px;align-items:end}.run-title>p{text-align:right;color:var(--muted)}figure{margin:8px 0 24px}figure img{display:block;width:100%;height:auto;border:2px solid var(--ink);background:#ddd}figcaption{font-size:.78rem;color:var(--muted);margin-top:6px}.steps{display:grid;gap:12px}.step{border-top:2px solid;padding-top:12px}.step header{display:grid;grid-template-columns:36px 1fr auto;gap:8px;align-items:start}.step h3{font-size:1rem;margin:0}.step header p{font-size:.78rem;color:var(--muted);overflow-wrap:anywhere}.number{display:grid;place-items:center;background:var(--blue);color:#fff;width:30px;height:30px;border-radius:50%;font-weight:800}.step>header>strong{text-transform:uppercase;font-size:.72rem;border:2px solid;padding:3px}.step.fail>header>strong{color:var(--bruise)}.step.warn>header>strong{color:#694b00}.step.pass>header>strong{color:var(--leaf)}dl{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:8px 0}dl div{min-width:0}dt{font-size:.7rem;text-transform:uppercase;color:var(--muted)}dd{margin:0;overflow-wrap:anywhere}code,kbd{font-family:inherit;background:#e9dfc8;padding:2px 4px}ul{padding-left:20px;margin-bottom:8px}footer{display:flex;justify-content:space-between;gap:24px;border-top:3px solid;margin-top:64px;padding:24px 0;font-size:.8rem;color:var(--muted)}:focus-visible{outline:3px solid var(--yellow);outline-offset:3px;box-shadow:0 0 0 5px var(--ink)}@media(max-width:760px){.runs{grid-template-columns:1fr}.summary{padding-top:40px}.run{padding:14px}.run-title{align-items:start}.step header{grid-template-columns:36px 1fr}.step header>strong{grid-column:2}.mast{padding-top:max(20px,env(safe-area-inset-top))}dl{grid-template-columns:1fr}footer{flex-direction:column}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;animation-duration:.01ms!important;transition-duration:.01ms!important}}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn escapes_untrusted_content() {
        assert_eq!(esc("<script>\"&"), "&lt;script&gt;&quot;&amp;");
    }
}
